### ISSUE TITLE
Modular M14 Rifle

### ISSUE THREAD

**Issue by SpypigDev** [SpypigDev/cmss13-Medpve#2]

**Comment by Crimsonzeke** [comment]
Notes:

10x24mm Ammo. Custom Magazine, two types of special ammo. Hollow-Point and APFSDS-Prototype (AP on steroids)

Attachments: Reflex sight, 6x Scope and Suppressor (For Now, custom attachments planned; AT3 Low Profile Sight)

Issued as; DMR for specialized Marines, or as personal weapons for Squad Leads.
